yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),

    path('', views.index, name='index'),
]

yatube/users/urls.py
import django.contrib.auth.views as Auth
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'),
    path(
        'login/',
        Auth.LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        Auth.LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'password_reset/done/',
        Auth.PasswordResetDoneView.as_view
        (template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_reset/',
        Auth.PasswordResetView.as_view
        (template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'reset/done/',
        Auth.PasswordResetCompleteView.as_view
        (template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'reset/<uidb64>/<token>/',
        Auth.PasswordResetConfirmView.as_view
        (template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'password_change/',
        Auth.PasswordChangeView.as_view
        (template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        Auth.PasswordChangeDoneView.as_view
        (template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
  <div class="footer-copyright text-center py-3">© {{ year }} Copyright 
    <p><span style="color:red">Ya</span>tube</p> 
  </div>    
</footer>

yatube/templates/includes/form_errors.html
{% load user_filters %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}            
            <div class="alert alert-danger">
                {{ error|escape }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ error|escape }}
        </div>
    {% endfor %}
{% endif %}

yatube/templates/includes/form_errors_and_fields.html
{% load user_filters %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}            
            <div class="alert alert-danger">
                {{ error|escape }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ error|escape }}
        </div>
    {% endfor %}
{% endif %}

{% csrf_token %}

{% for field in form %}
    <div class="form-group row my-3"
        {% if field.field.required %} 
            aria-required="true"
        {% else %}
            aria-required="false"
        {% endif %}
            >
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
          {% if field.field.required %}
            <span class="required text-danger">*</span>
          {% endif %}
        </label>
        <div>
          {{ field|addclass:'form-control' }}
          {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
            </small>
          {% endif %}
        </div>
    </div>
{% endfor %}

yatube/templates/includes/form_fields.html
{% load user_filters %}

{% for field in form %}
    <div class="form-group row my-3"
        {% if field.field.required %} 
            aria-required="true"
        {% else %}
            aria-required="false"
        {% endif %}
            >
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
          {% if field.field.required %}
            <span class="required text-danger">*</span>
          {% endif %}
        </label>
        <div>
          {{ field|addclass:'form-control' }}
          {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
            </small>
          {% endif %}
        </div>
    </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}

<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>      
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}" href="{% url 'users:password_change_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
        </li>           
        {% endif %}
        {% endwith %}
      </ul>      
    </div>
  </nav>      
</header>