yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),

    path('', views.index, name='index'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from .constants import MAX_LENGHT_OF_RETURN_TEXT
from core.models import TextAndPubDateModel

User = get_user_model()


class Post(TextAndPubDateModel):
    """Модель Post используется для хранения постов в блоге.
    У пользователя есть возможность публиковать посты в общей ленте
    и выбирать тематическую группу, в которой появится его пост.
    """

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:MAX_LENGHT_OF_RETURN_TEXT]


class Group(models.Model):
    """Модель Group для сообществ. Сообщества создаются администратором сайта,
    у посетителей нет возможности их добавлять. При публикации записи автор
    может выбрать одно сообщество и отправить туда свой пост.
    """

    title = models.CharField(
        max_length=200,
        verbose_name="название сообщества",
    )
    slug = models.SlugField(
        unique=True,
        verbose_name="уникальный адрес сообщества",
    )
    description = models.TextField(
        verbose_name="описание",
    )

    def __str__(self):
        return self.title


class Comment(TextAndPubDateModel):
    """Комментирование постов."""
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий',
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )


class Follow(models.Model):
    """Подписки на авторов."""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор, на которого подписываются',
    )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    """Форма создания поста."""

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    """Форма создания комментария к посту."""

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow
from .utils import get_page
from .constants import CASH_TIME_SEC


@cache_page(CASH_TIME_SEC, key_prefix='index_page')
def index(request):
    """Главная страница."""

    template = 'posts/index.html'
    post_list = Post.objects.select_related('group', 'author').all()
    page_obj = get_page(request, post_list)
    context = {
        'page_obj': page_obj,
    }

    return render(request, template, context)


def group_posts(request, slug):
    """Страница сообщества."""

    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author')
    page_obj = get_page(request, post_list)

    context = {
        'group': group,
        'page_obj': page_obj,
    }

    return render(request, template, context)


def profile(request, username):
    """Персональная страница пользователя."""

    template = 'posts/profile.html'
    author = User.objects.get(username=username)
    post_list = author.posts.select_related('group')
    page_obj = get_page(request, post_list)

    following = (
        request.user.is_authenticated
        and request.user != author
        and Follow.objects.filter(user=request.user, author=author).exists()
    )

    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }

    return render(request, template, context)


def post_detail(request, post_id):
    """Страница просмотра отдельного поста."""

    template = 'posts/post_detail.html'
    post = get_object_or_404(
        Post.objects.select_related(
            'group',
            'author'
        ), id=post_id
    )
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }

    return render(request, template, context)


@login_required
def post_create(request):
    """Страница для создания новой записи."""

    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()

        return redirect('posts:profile', request.user)

    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    """Страница для редактирования поста."""

    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)

    if request.user != post.author:
        return redirect('posts:post_detail', post.id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        form.save()

        return redirect('posts:post_detail', post.id)

    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }

    return render(request, template, context)


@login_required
def add_comment(request, post_id):

    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post.id)


@login_required
def follow_index(request):
    """Страница с лентой постов авторов, на которых подписан пользователь."""

    template = 'posts/follow.html'

    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = get_page(request, post_list)
    context = {
        'page_obj': page_obj,
    }

    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Подписаться на автора."""

    author = get_object_or_404(User, username=username)
    if not (
        request.user == author
        or Follow.objects.filter(user=request.user, author=author).exists()
    ):
        Follow.objects.create(user=request.user, author=author)

    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Отписка от автора."""

    author = get_object_or_404(User, username=username)

    Follow.objects.filter(user=request.user, author=author).delete()

    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Новый пост
  {% endif %}   
{% endblock %}

{% block content %}   
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Новый пост
            {% endif %}             
          </div>
          <div class="card-body">
            {% include 'includes/form_errors.html' %}                  
            <form method="post" enctype="multipart/form-data"
              {% if is_edit %}
                action="{% url 'posts:post_edit' post.id %}"            
              {% else %}
                action="{% url 'posts:post_create' %}"              
              {% endif %}
              >            
              {% csrf_token %}
              {% include 'includes/form_fields.html' %}      
              <div class="d-flex justify-content-end">                
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}                      
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}        

    

yatube/templates/posts/follow.html
{% extends 'base.html' %}
  
{% block title %}
  Мои подписки 
{% endblock %} 
 
{% block content %}
  <h1> Мои подписки </h1>
  {% include 'posts/includes/switcher.html' %}  
  {% for post in page_obj %}
    {% include 'posts/includes/post_card.html' %}        
    {% if not forloop.last %} <hr> {% endif %}
  {% endfor %}  
  {% include 'posts/includes/paginator.html' %}                   
{% endblock %}  

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %} 

{% block content %}
  <h1> {{ group.title }} </h1>
  <p>
    {{ group.description|linebreaksbr }}     
  </p>
  {% for post in page_obj %}
    {% include 'posts/includes/post_card.html' %}
    {% if not forloop.last %} <hr> {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}      
{% endblock %}
  

yatube/templates/posts/index.html
{% extends 'base.html' %}
   
{% block title %}
  Последние обновления на сайте 
{% endblock %} 
 
{% block content %}
  <h1> Последние обновления на сайте </h1>
  {% include 'posts/includes/switcher.html' %}
  {% load cache %}
  {% cache 20 sidebar %}
  {% for post in page_obj %}
    {% include 'posts/includes/post_card.html' %}        
    {% if not forloop.last %} <hr> {% endif %}
  {% endfor %}
  {% endcache %} 
  {% include 'posts/includes/paginator.html' %}                   
{% endblock %}  

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Пост {{ post|truncatechars:30 }}
{% endblock %} 
    
{% block content %}  
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group.title }}
          <a href="{% url 'posts:group_list' post.group.slug %}">
          <br> все записи группы</a>
        </li>            
        {% endif %}           
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: {{ post.author.posts.count }}
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaksbr}}
      </p>
      {% if post.author == request.user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a>
      {% endif %}  
    </article>
    {% include 'posts/includes/comment_form.html' %}
  </div> 
{% endblock %}    

yatube/templates/posts/profile.html
{% extends 'base.html' %} 

{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block content %}      
  <h1> Все посты пользователя {{ author.get_full_name }} </h1>
  <h3> Всего постов: {{ author.posts.count }} </h3> 
  <h3> Всего подписчиков: {{ author.following.count }} </h3> 
  <h3> Всего подписок: {{ author.follower.count }} </h3>   
  
  {% if request.user.is_authenticated and request.user != author %}
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
       <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
    {% endif %}
  {% endif %}  
  {% for post in page_obj %}        
    {% include 'posts/includes/post_card.html' %}    
    {% if not forloop.last %} <hr> {% endif %}
  {% endfor %}     
    
  {% include 'posts/includes/paginator.html' %}
{% endblock %}